# render.yaml
services:
  - type: web
    name: soul-yatri-backend
    env: python
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: soulyatri.json
